---
name: ci-cargo-dimension

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '**.md'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get nightly toolchain from file
        id: nightly-toolchain
        run: echo "::set-output name=version::$(cat resources/rust-toolchain.in)"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ steps.nightly-toolchain.outputs.version }}
          profile: minimal
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: fmt -- --check

      - name: Audit
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: audit

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: clippy --all-targets

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: test
